[build]
  command = "pip install -r requirements.txt"
  functions = "netlify/functions"
  publish = "templates"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app"
  status = 200
[build]
  environment = { PYTHON_VERSION = "3.9" }