[build]
  command = "pip install -r requirements.txt"
  functions = "netlify/functions"
  publish = "templates"
  publish = "static"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app"
  status = 200
